runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: enum
  version: latest
- name: pytz
  version: "2016.4"
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: favicon.png
  upload: favicon\.png
- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301
- url: /.*
  script: main.app
  secure: always
  redirect_http_response_code: 301

env_variables:
  # Replace with your Firebase project ID.
  FIREBASE_PROJECT_ID: 'synapcards-178123'
